/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_box2d_Controller */

#ifndef _Included_com_badlogic_gdx_physics_box2d_Controller
#define _Included_com_badlogic_gdx_physics_box2d_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_box2d_Controller
 * Method:    jniAddBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_Controller_jniAddBody
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_Controller
 * Method:    jniRemoveBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_Controller_jniRemoveBody
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_Controller
 * Method:    jniClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_Controller_jniClear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
